name: EnhanceDocs Github Action
description: 'Setup EnhanceDocs CLI in your Github Actions workflow.'
author: EnhanceDocs

inputs:
  api-key:
    description: 'Your EnhanceDocs Secret API Key.'
    required: true

runs:
  using: "composite"
  steps:
    - run: npm install -g enhancedocs@0.4.0
      shell: bash
    - run: echo "ENHANCEDOCS_API_KEY=${{ inputs.api-key }}" >> $GITHUB_ENV
      shell: bash

branding:
  icon: 'book'
  color: 'blue'
